packages:
  - packages/*

catalog:
  '@types/node': ^25.2.3
  '@ungap/with-resolvers': ^0.1.0
  '@vitest/browser-playwright': ^4.0.18
  '@vitest/coverage-v8': ^4.0.18
  playwright: ^1.58.2
  tsup: ^8.5.1
  vitest: 4.0.18
