packages:
  - packages/*

catalog:
  '@types/node': ^24.0.13
  '@ungap/with-resolvers': ^0.1.0
  '@vitest/browser': ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  playwright: ^1.53.0
  tsup: ^8.5.0
  vitest: 3.2.4
